"""add post title

Revision ID: 356c42d4504d
Revises: 80896377dd32
Create Date: 2024-10-30 22:11:32.913009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356c42d4504d'
down_revision = '80896377dd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
